/* 
 * Copyright PT Len Industri (Persero) 

 *  
 * TO PT LEN INDUSTRI (PERSERO), AS APPLICABLE, AND SHALL NOT BE USED IN ANY WAY
 * OTHER THAN BEFOREHAND AGREED ON BY PT LEN INDUSTRI (PERSERO), NOR BE REPRODUCED
 * OR DISCLOSED TO THIRD PARTIES WITHOUT PRIOR WRITTEN AUTHORIZATION BY
 * PT LEN INDUSTRI (PERSERO), AS APPLICABLE
 */

package org.len.tdl.sync_view;

import java.awt.Color;
import org.len.tdl.view.ryt.MainTest;

/**
 *
 * @author yudha
 */

/**
 * 
 * This is sync_view Jframe form class
 */
public class sync_view extends javax.swing.JFrame {

    /**
     * Creates new form sync_view
     */
    MainTest main ;
    public sync_view() {
        initComponents();
    }
    
    public sync_view(MainTest frame){
        initComponents();
        main = frame;
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnpu17 = new javax.swing.JLabel();
        lnpu15 = new javax.swing.JLabel();
        lnpu16 = new javax.swing.JLabel();
        lnpu13 = new javax.swing.JLabel();
        lnpu14 = new javax.swing.JLabel();
        lnpu11 = new javax.swing.JLabel();
        lnpu12 = new javax.swing.JLabel();
        lnpu9 = new javax.swing.JLabel();
        lnpu10 = new javax.swing.JLabel();
        lnpu19 = new javax.swing.JLabel();
        lnpu18 = new javax.swing.JLabel();
        lnpu20 = new javax.swing.JLabel();
        lnpu1 = new javax.swing.JLabel();
        lnpu8 = new javax.swing.JLabel();
        lnpu5 = new javax.swing.JLabel();
        lnpu4 = new javax.swing.JLabel();
        lnpu3 = new javax.swing.JLabel();
        lnpu2 = new javax.swing.JLabel();
        lnpu7 = new javax.swing.JLabel();
        lnpu6 = new javax.swing.JLabel();
        lnpu21 = new javax.swing.JLabel();
        lnpu22 = new javax.swing.JLabel();
        lnpu23 = new javax.swing.JLabel();
        lnpu24 = new javax.swing.JLabel();
        lnpu25 = new javax.swing.JLabel();
        lnpu26 = new javax.swing.JLabel();
        lnpu27 = new javax.swing.JLabel();
        lnpu28 = new javax.swing.JLabel();
        lnpu29 = new javax.swing.JLabel();
        lnpu30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NPU Indicator");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lnpu17.setBackground(new java.awt.Color(204, 204, 204));
        lnpu17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu17.setText("17");
        lnpu17.setOpaque(true);
        lnpu17.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu15.setBackground(new java.awt.Color(204, 204, 204));
        lnpu15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu15.setText("15");
        lnpu15.setOpaque(true);
        lnpu15.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu16.setBackground(new java.awt.Color(204, 204, 204));
        lnpu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu16.setText("16");
        lnpu16.setOpaque(true);
        lnpu16.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu13.setBackground(new java.awt.Color(204, 204, 204));
        lnpu13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu13.setText("13");
        lnpu13.setOpaque(true);
        lnpu13.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu14.setBackground(new java.awt.Color(204, 204, 204));
        lnpu14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu14.setText("14");
        lnpu14.setOpaque(true);
        lnpu14.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu11.setBackground(new java.awt.Color(204, 204, 204));
        lnpu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu11.setText("11");
        lnpu11.setOpaque(true);
        lnpu11.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu12.setBackground(new java.awt.Color(204, 204, 204));
        lnpu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu12.setText("12");
        lnpu12.setOpaque(true);
        lnpu12.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu9.setBackground(new java.awt.Color(204, 204, 204));
        lnpu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu9.setText("9");
        lnpu9.setOpaque(true);
        lnpu9.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu10.setBackground(new java.awt.Color(204, 204, 204));
        lnpu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu10.setText("10");
        lnpu10.setOpaque(true);
        lnpu10.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu19.setBackground(new java.awt.Color(204, 204, 204));
        lnpu19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu19.setText("19");
        lnpu19.setOpaque(true);
        lnpu19.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu18.setBackground(new java.awt.Color(204, 204, 204));
        lnpu18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu18.setText("18");
        lnpu18.setOpaque(true);
        lnpu18.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu20.setBackground(new java.awt.Color(204, 204, 204));
        lnpu20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu20.setText("20");
        lnpu20.setOpaque(true);
        lnpu20.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu1.setBackground(new java.awt.Color(204, 204, 204));
        lnpu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu1.setText("1");
        lnpu1.setOpaque(true);
        lnpu1.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu8.setBackground(new java.awt.Color(204, 204, 204));
        lnpu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu8.setText("8");
        lnpu8.setOpaque(true);
        lnpu8.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu5.setBackground(new java.awt.Color(204, 204, 204));
        lnpu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu5.setText("5");
        lnpu5.setOpaque(true);
        lnpu5.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu4.setBackground(new java.awt.Color(204, 204, 204));
        lnpu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu4.setText("4");
        lnpu4.setOpaque(true);
        lnpu4.setPreferredSize(new java.awt.Dimension(28, 15));
        lnpu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnpu4MouseClicked(evt);
            }
        });

        lnpu3.setBackground(new java.awt.Color(204, 204, 204));
        lnpu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu3.setText("3");
        lnpu3.setOpaque(true);
        lnpu3.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu2.setBackground(new java.awt.Color(204, 204, 204));
        lnpu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu2.setText("2");
        lnpu2.setOpaque(true);
        lnpu2.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu7.setBackground(new java.awt.Color(204, 204, 204));
        lnpu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu7.setText("7");
        lnpu7.setOpaque(true);
        lnpu7.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu6.setBackground(new java.awt.Color(204, 204, 204));
        lnpu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu6.setText("6");
        lnpu6.setOpaque(true);
        lnpu6.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu21.setBackground(new java.awt.Color(204, 204, 204));
        lnpu21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu21.setText("21");
        lnpu21.setOpaque(true);
        lnpu21.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu22.setBackground(new java.awt.Color(204, 204, 204));
        lnpu22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu22.setText("22");
        lnpu22.setOpaque(true);
        lnpu22.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu23.setBackground(new java.awt.Color(204, 204, 204));
        lnpu23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu23.setText("23");
        lnpu23.setOpaque(true);
        lnpu23.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu24.setBackground(new java.awt.Color(204, 204, 204));
        lnpu24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu24.setText("24");
        lnpu24.setOpaque(true);
        lnpu24.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu25.setBackground(new java.awt.Color(204, 204, 204));
        lnpu25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu25.setText("25");
        lnpu25.setOpaque(true);
        lnpu25.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu26.setBackground(new java.awt.Color(204, 204, 204));
        lnpu26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu26.setText("26");
        lnpu26.setOpaque(true);
        lnpu26.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu27.setBackground(new java.awt.Color(204, 204, 204));
        lnpu27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu27.setText("27");
        lnpu27.setOpaque(true);
        lnpu27.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu28.setBackground(new java.awt.Color(204, 204, 204));
        lnpu28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu28.setText("28");
        lnpu28.setOpaque(true);
        lnpu28.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu29.setBackground(new java.awt.Color(204, 204, 204));
        lnpu29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu29.setText("29");
        lnpu29.setOpaque(true);
        lnpu29.setPreferredSize(new java.awt.Dimension(28, 15));

        lnpu30.setBackground(new java.awt.Color(204, 204, 204));
        lnpu30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnpu30.setText("30");
        lnpu30.setOpaque(true);
        lnpu30.setPreferredSize(new java.awt.Dimension(28, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lnpu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnpu11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lnpu21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnpu22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnpu23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnpu24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnpu25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnpu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnpu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lnpu12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lnpu22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lnpu13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lnpu23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lnpu14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lnpu24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lnpu15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lnpu25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lnpu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lnpu26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lnpu30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnpu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnpu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnpu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnpu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnpu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnpu21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnpu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnpu4MouseClicked
    }//GEN-LAST:event_lnpu4MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        main.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    /**
     * Method to show NPU
     */
    public void GUI_Show_NPU_Tick(int npu) {
        lnpu1.setForeground(Color.BLACK);
        lnpu2.setForeground(Color.BLACK);
        lnpu3.setForeground(Color.BLACK);
        lnpu4.setForeground(Color.BLACK);
        lnpu5.setForeground(Color.BLACK);
        lnpu6.setForeground(Color.BLACK);
        lnpu7.setForeground(Color.BLACK);
        lnpu8.setForeground(Color.BLACK);
        lnpu9.setForeground(Color.BLACK);
        lnpu10.setForeground(Color.BLACK);
        lnpu11.setForeground(Color.BLACK);
        lnpu12.setForeground(Color.BLACK);
        lnpu13.setForeground(Color.BLACK);
        lnpu14.setForeground(Color.BLACK);
        lnpu15.setForeground(Color.BLACK);
        lnpu16.setForeground(Color.BLACK);
        lnpu17.setForeground(Color.BLACK);
        lnpu18.setForeground(Color.BLACK);
        lnpu19.setForeground(Color.BLACK);
        lnpu20.setForeground(Color.BLACK);
        lnpu21.setForeground(Color.BLACK);
        lnpu22.setForeground(Color.BLACK);
        lnpu23.setForeground(Color.BLACK);
        lnpu24.setForeground(Color.BLACK);
        lnpu25.setForeground(Color.BLACK);
        lnpu26.setForeground(Color.BLACK);
        lnpu27.setForeground(Color.BLACK);
        lnpu28.setForeground(Color.BLACK);
        lnpu29.setForeground(Color.BLACK);
        lnpu30.setForeground(Color.BLACK);

        switch (npu) {
            case 1:
                lnpu1.setForeground(Color.RED);
                break;
            case 2:
                lnpu2.setForeground(Color.RED);
                break;
            case 3:
                lnpu3.setForeground(Color.RED);
                break;
            case 4:
                lnpu4.setForeground(Color.RED);
                break;
            case 5:
                lnpu5.setForeground(Color.RED);
                break;
            case 6:
                lnpu6.setForeground(Color.RED);
                break;
            case 7:
                lnpu7.setForeground(Color.RED);
                break;
            case 8:
                lnpu8.setForeground(Color.RED);
                break;
            case 9:
                lnpu9.setForeground(Color.RED);
                break;
            case 10:
                lnpu10.setForeground(Color.RED);
                break;
            case 11:
                lnpu11.setForeground(Color.RED);
                break;
            case 12:
                lnpu12.setForeground(Color.RED);
                break;
            case 13:
                lnpu13.setForeground(Color.RED);
                break;
            case 14:
                lnpu14.setForeground(Color.RED);
                break;
            case 15:
                lnpu15.setForeground(Color.RED);
                break;
            case 16:
                lnpu16.setForeground(Color.RED);
                break;
            case 17:
                lnpu17.setForeground(Color.RED);
                break;
            case 18:
                lnpu18.setForeground(Color.RED);
                break;
            case 19:
                lnpu19.setForeground(Color.RED);
                break;
            case 20:
                lnpu20.setForeground(Color.RED);
                break;
            case 21:
                lnpu21.setForeground(Color.RED);
                break;

            case 22:
                lnpu22.setForeground(Color.RED);
                break;

            case 23:
                lnpu23.setForeground(Color.RED);
                break;

            case 24:
                lnpu24.setForeground(Color.RED);
                break;

            case 25:
                lnpu25.setForeground(Color.RED);
                break;

            case 26:
                lnpu26.setForeground(Color.RED);
                break;

            case 27:
                lnpu27.setForeground(Color.RED);
                break;

            case 28:
                lnpu28.setForeground(Color.RED);
                break;

            case 29:
                lnpu29.setForeground(Color.RED);
                break;

            case 30:
                lnpu30.setForeground(Color.RED);
                break;
        }

    }

     /**
     * Method to show NPU that active
     */
    public void GUI_Show_NPU_Active(int[] npu_life, int lastnpu) {
        if (npu_life[1] == 0) {
            lnpu1.setBackground(Color.GRAY);
        } else if (lastnpu == 1) {
            lnpu1.setBackground(Color.RED);
        } else {
            lnpu1.setBackground(Color.YELLOW);
        }

        if (npu_life[2] == 0) {
            lnpu2.setBackground(Color.GRAY);
        } else if (lastnpu == 2) {
            lnpu2.setBackground(Color.RED);
        } else {
            lnpu2.setBackground(Color.YELLOW);
        }


        if (npu_life[3] == 0) {
            lnpu3.setBackground(Color.GRAY);
        } else if (lastnpu == 3) {
            lnpu3.setBackground(Color.RED);
        } else {
            lnpu3.setBackground(Color.YELLOW);
        }


        if (npu_life[4] == 0) {
            lnpu4.setBackground(Color.GRAY);
        } else if (lastnpu == 4) {
            lnpu4.setBackground(Color.RED);
        } else {
            lnpu4.setBackground(Color.YELLOW);
        }


        if (npu_life[5] == 0) {
            lnpu5.setBackground(Color.GRAY);
        } else if (lastnpu == 5) {
            lnpu5.setBackground(Color.RED);
        } else {
            lnpu5.setBackground(Color.YELLOW);
        }


        if (npu_life[6] == 0) {
            lnpu6.setBackground(Color.GRAY);
        } else if (lastnpu == 6) {
            lnpu6.setBackground(Color.RED);
        } else {
            lnpu6.setBackground(Color.YELLOW);
        }


        if (npu_life[7] == 0) {
            lnpu7.setBackground(Color.GRAY);
        } else if (lastnpu == 7) {
            lnpu7.setBackground(Color.RED);
        } else {
            lnpu7.setBackground(Color.YELLOW);
        }


        if (npu_life[8] == 0) {
            lnpu8.setBackground(Color.GRAY);
        } else if (lastnpu == 8) {
            lnpu8.setBackground(Color.RED);
        } else {
            lnpu8.setBackground(Color.YELLOW);
        }


        if (npu_life[9] == 0) {
            lnpu9.setBackground(Color.GRAY);
        } else if (lastnpu == 9) {
            lnpu9.setBackground(Color.RED);
        } else {
            lnpu9.setBackground(Color.YELLOW);
        }


        if (npu_life[10] == 0) {
            lnpu10.setBackground(Color.GRAY);
        } else if (lastnpu == 10) {
            lnpu10.setBackground(Color.RED);
        } else {
            lnpu10.setBackground(Color.YELLOW);
        }


        if (npu_life[11] == 0) {
            lnpu11.setBackground(Color.GRAY);
        } else if (lastnpu == 11) {
            lnpu11.setBackground(Color.RED);
        } else {
            lnpu11.setBackground(Color.YELLOW);
        }

        if (npu_life[12] == 0) {
            lnpu12.setBackground(Color.GRAY);
        } else if (lastnpu == 12) {
            lnpu12.setBackground(Color.RED);
        } else {
            lnpu12.setBackground(Color.YELLOW);
        }


        if (npu_life[13] == 0) {
            lnpu13.setBackground(Color.GRAY);
        } else if (lastnpu == 13) {
            lnpu13.setBackground(Color.RED);
        } else {
            lnpu13.setBackground(Color.YELLOW);
        }


        if (npu_life[14] == 0) {
            lnpu14.setBackground(Color.GRAY);
        } else if (lastnpu == 14) {
            lnpu14.setBackground(Color.RED);
        } else {
            lnpu14.setBackground(Color.YELLOW);
        }


        if (npu_life[15] == 0) {
            lnpu15.setBackground(Color.GRAY);
        } else if (lastnpu == 15) {
            lnpu15.setBackground(Color.RED);
        } else {
            lnpu15.setBackground(Color.YELLOW);
        }


        if (npu_life[16] == 0) {
            lnpu16.setBackground(Color.GRAY);
        } else if (lastnpu == 16) {
            lnpu16.setBackground(Color.RED);
        } else {
            lnpu16.setBackground(Color.YELLOW);
        }


        if (npu_life[17] == 0) {
            lnpu17.setBackground(Color.GRAY);
        } else if (lastnpu == 17) {
            lnpu17.setBackground(Color.RED);
        } else {
            lnpu17.setBackground(Color.YELLOW);
        }


        if (npu_life[18] == 0) {
            lnpu18.setBackground(Color.GRAY);
        } else if (lastnpu == 18) {
            lnpu18.setBackground(Color.RED);
        } else {
            lnpu18.setBackground(Color.YELLOW);
        }

      
        if (npu_life[19] == 0) {
            lnpu19.setBackground(Color.GRAY);
        } else if (lastnpu == 19) {
            lnpu19.setBackground(Color.RED);
        } else {
            lnpu19.setBackground(Color.YELLOW);
        }

       
        if (npu_life[20] == 0) {
            lnpu20.setBackground(Color.GRAY);
        } else if (lastnpu == 20) {
            lnpu20.setBackground(Color.RED);
        } else {
            lnpu20.setBackground(Color.YELLOW);
        }

        if (npu_life[21] == 0) {
            lnpu21.setBackground(Color.GRAY);
        } else if (lastnpu == 21) {
            lnpu21.setBackground(Color.RED);
        } else {
            lnpu21.setBackground(Color.YELLOW);
        }

        if (npu_life[22] == 0) {
            lnpu22.setBackground(Color.GRAY);
        } else if (lastnpu == 22) {
            lnpu22.setBackground(Color.RED);
        } else {
            lnpu22.setBackground(Color.YELLOW);
        }

        if (npu_life[23] == 0) {
            lnpu23.setBackground(Color.GRAY);
        } else if (lastnpu == 23) {
            lnpu23.setBackground(Color.RED);
        } else {
            lnpu23.setBackground(Color.YELLOW);
        }

        if (npu_life[24] == 0) {
            lnpu24.setBackground(Color.GRAY);
        } else if (lastnpu == 24) {
            lnpu24.setBackground(Color.RED);
        } else {
            lnpu24.setBackground(Color.YELLOW);
        }

        if (npu_life[25] == 0) {
            lnpu25.setBackground(Color.GRAY);
        } else if (lastnpu == 25) {
            lnpu25.setBackground(Color.RED);
        } else {
            lnpu25.setBackground(Color.YELLOW);
        }

        if (npu_life[26] == 0) {
            lnpu26.setBackground(Color.GRAY);
        } else if (lastnpu == 26) {
            lnpu26.setBackground(Color.RED);
        } else {
            lnpu26.setBackground(Color.YELLOW);
        }

        if (npu_life[27] == 0) {
            lnpu27.setBackground(Color.GRAY);
        } else if (lastnpu == 27) {
            lnpu27.setBackground(Color.RED);
        } else {
            lnpu27.setBackground(Color.YELLOW);
        }

        if (npu_life[28] == 0) {
            lnpu28.setBackground(Color.GRAY);
        } else if (lastnpu == 28) {
            lnpu28.setBackground(Color.RED);
        } else {
            lnpu28.setBackground(Color.YELLOW);
        }

        if (npu_life[29] == 0) {
            lnpu29.setBackground(Color.GRAY);
        } else if (lastnpu == 29) {
            lnpu29.setBackground(Color.RED);
        } else {
            lnpu29.setBackground(Color.YELLOW);
        }

        if (npu_life[30] == 0) {
            lnpu30.setBackground(Color.GRAY);
        } else if (lastnpu == 30) {
            lnpu30.setBackground(Color.RED);
        } else {
            lnpu30.setBackground(Color.YELLOW);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sync_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sync_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sync_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sync_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sync_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lnpu1;
    private javax.swing.JLabel lnpu10;
    private javax.swing.JLabel lnpu11;
    private javax.swing.JLabel lnpu12;
    private javax.swing.JLabel lnpu13;
    private javax.swing.JLabel lnpu14;
    private javax.swing.JLabel lnpu15;
    private javax.swing.JLabel lnpu16;
    private javax.swing.JLabel lnpu17;
    private javax.swing.JLabel lnpu18;
    private javax.swing.JLabel lnpu19;
    private javax.swing.JLabel lnpu2;
    private javax.swing.JLabel lnpu20;
    private javax.swing.JLabel lnpu21;
    private javax.swing.JLabel lnpu22;
    private javax.swing.JLabel lnpu23;
    private javax.swing.JLabel lnpu24;
    private javax.swing.JLabel lnpu25;
    private javax.swing.JLabel lnpu26;
    private javax.swing.JLabel lnpu27;
    private javax.swing.JLabel lnpu28;
    private javax.swing.JLabel lnpu29;
    private javax.swing.JLabel lnpu3;
    private javax.swing.JLabel lnpu30;
    private javax.swing.JLabel lnpu4;
    private javax.swing.JLabel lnpu5;
    private javax.swing.JLabel lnpu6;
    private javax.swing.JLabel lnpu7;
    private javax.swing.JLabel lnpu8;
    private javax.swing.JLabel lnpu9;
    // End of variables declaration//GEN-END:variables
}