/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.len.tdl.share;

import java.awt.Color;
import jssc.SerialPortList;
import org.len.tdl.common.DataListener;


/**
 *
 * @author riyanto
 */
public class GuiGpsShare extends javax.swing.JFrame {

    private final MainRxGps mainRxGps = new MainRxGps();
    private final MainTxGps mainTxGps1 = new MainTxGps();
    private final MainTxGps mainTxGps2 = new MainTxGps();

    private void GUI_addPortList() {
        jComboBoxGpsPort.removeAllItems();
        String[] portNames = SerialPortList.getPortNames();
        for (String portName : portNames) {
            jComboBoxGpsPort.addItem(portName);
        }
    }

    private class SerialGpsParserReceive implements DataListener {

        @Override
        public void dataReceive(byte[] aData, int aType) {
            mainTxGps1.sendGpsGprmc(aData, Integer.valueOf(jTextFieldIpPortUdpGps1.getText()), jTextFieldIpAddressUdpGps1.getText());
            mainTxGps2.sendGpsGprmc(aData, Integer.valueOf(jTextFieldIpPortUdpGps2.getText()), jTextFieldIpAddressUdpGps2.getText());

            if (jCheckBoxLoggerGpsEnable.isSelected()) {
                jTextAreaLoggerGps.append(new String(aData) + "\n");
            }
        }

        @Override
        public void infoReceive(byte[] track) {
            //System.out.println("SEND OWN TRACK GPS TO CCD");
        }
    }

    /**
     * Creates new form UdpGpsShare
     */
    public GuiGpsShare() {
        initComponents();

        GUI_addPortList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIpPortUdpGps1 = new javax.swing.JTextField();
        jTextFieldIpAddressUdpGps1 = new javax.swing.JTextField();
        jButtonSetSocketUdpGps = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxGpsPort = new javax.swing.JComboBox<>();
        jTextFieldGpsBaudrate = new javax.swing.JTextField();
        jButtonGpsConnect = new javax.swing.JButton();
        jLabelStatusGps = new javax.swing.JLabel();
        jTextFieldIpPortUdpGps2 = new javax.swing.JTextField();
        jTextFieldIpAddressUdpGps2 = new javax.swing.JTextField();
        jCheckBoxLoggerGpsEnable = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLoggerGps = new javax.swing.JTextArea();
        jButtonClearLoggerGps = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GPS Shared");
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setText("IP Address");

        jLabel14.setText("Port");

        jTextFieldIpPortUdpGps1.setText("4242");
        jTextFieldIpPortUdpGps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIpPortUdpGps1ActionPerformed(evt);
            }
        });

        jTextFieldIpAddressUdpGps1.setText("localhost");
        jTextFieldIpAddressUdpGps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIpAddressUdpGps1ActionPerformed(evt);
            }
        });

        jButtonSetSocketUdpGps.setText("Set");
        jButtonSetSocketUdpGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetSocketUdpGpsActionPerformed(evt);
            }
        });

        jLabel11.setText("Port");

        jLabel12.setText("Baudrate");

        jComboBoxGpsPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGpsPortActionPerformed(evt);
            }
        });

        jTextFieldGpsBaudrate.setText("4800");

        jButtonGpsConnect.setText("Connect");
        jButtonGpsConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGpsConnectActionPerformed(evt);
            }
        });

        jLabelStatusGps.setText("Disconnet");

        jTextFieldIpPortUdpGps2.setText("4243");
        jTextFieldIpPortUdpGps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIpPortUdpGps2ActionPerformed(evt);
            }
        });

        jTextFieldIpAddressUdpGps2.setText("localhost");
        jTextFieldIpAddressUdpGps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIpAddressUdpGps2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSetSocketUdpGps))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIpAddressUdpGps1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIpPortUdpGps1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIpPortUdpGps2)
                                    .addComponent(jTextFieldIpAddressUdpGps2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxGpsPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldGpsBaudrate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jButtonGpsConnect)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusGps)
                .addGap(87, 87, 87))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxGpsPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGpsBaudrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButtonGpsConnect)
                    .addComponent(jLabelStatusGps))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIpAddressUdpGps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIpAddressUdpGps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIpPortUdpGps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldIpPortUdpGps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSetSocketUdpGps)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBoxLoggerGpsEnable.setSelected(true);
        jCheckBoxLoggerGpsEnable.setText("Show GPS Logger");

        jTextAreaLoggerGps.setColumns(20);
        jTextAreaLoggerGps.setRows(5);
        jScrollPane3.setViewportView(jTextAreaLoggerGps);

        jButtonClearLoggerGps.setText("Clear");
        jButtonClearLoggerGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearLoggerGpsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBoxLoggerGpsEnable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClearLoggerGps))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearLoggerGps)
                    .addComponent(jCheckBoxLoggerGpsEnable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIpPortUdpGps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIpPortUdpGps1ActionPerformed

    }//GEN-LAST:event_jTextFieldIpPortUdpGps1ActionPerformed

    private void jTextFieldIpAddressUdpGps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIpAddressUdpGps1ActionPerformed

    }//GEN-LAST:event_jTextFieldIpAddressUdpGps1ActionPerformed

    private void jButtonSetSocketUdpGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetSocketUdpGpsActionPerformed
        mainTxGps1.setSocket(Integer.valueOf(jTextFieldIpPortUdpGps1.getText()), jTextFieldIpAddressUdpGps1.getText());
        mainTxGps2.setSocket(Integer.valueOf(jTextFieldIpPortUdpGps2.getText()), jTextFieldIpAddressUdpGps2.getText());
    }//GEN-LAST:event_jButtonSetSocketUdpGpsActionPerformed

    private void jComboBoxGpsPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGpsPortActionPerformed
        mainRxGps.setPortName(jComboBoxGpsPort.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxGpsPortActionPerformed

    private void jButtonGpsConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGpsConnectActionPerformed

        if (mainRxGps.isGpsConnect()) {
            mainRxGps.removeListener();
            mainRxGps.disconnectGps();
        } else {
            mainRxGps.addListener(new SerialGpsParserReceive());
            mainRxGps.connectGps();
        }

        if (mainRxGps.isGpsConnect()) {
            jButtonGpsConnect.setText("Disconnect");
            jLabelStatusGps.setText("CONNECTED");
            jLabelStatusGps.setForeground(Color.blue);
        } else {
            jButtonGpsConnect.setText("Connect");
            jLabelStatusGps.setText("NOT CONNECTED");
            jLabelStatusGps.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonGpsConnectActionPerformed

    private void jButtonClearLoggerGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearLoggerGpsActionPerformed
        jTextAreaLoggerGps.setText("");
    }//GEN-LAST:event_jButtonClearLoggerGpsActionPerformed

    private void jTextFieldIpPortUdpGps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIpPortUdpGps2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIpPortUdpGps2ActionPerformed

    private void jTextFieldIpAddressUdpGps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIpAddressUdpGps2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIpAddressUdpGps2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiGpsShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiGpsShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiGpsShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiGpsShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiGpsShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearLoggerGps;
    private javax.swing.JButton jButtonGpsConnect;
    private javax.swing.JButton jButtonSetSocketUdpGps;
    private javax.swing.JCheckBox jCheckBoxLoggerGpsEnable;
    private javax.swing.JComboBox<String> jComboBoxGpsPort;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabelStatusGps;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaLoggerGps;
    private javax.swing.JTextField jTextFieldGpsBaudrate;
    private javax.swing.JTextField jTextFieldIpAddressUdpGps1;
    private javax.swing.JTextField jTextFieldIpAddressUdpGps2;
    private javax.swing.JTextField jTextFieldIpPortUdpGps1;
    private javax.swing.JTextField jTextFieldIpPortUdpGps2;
    // End of variables declaration//GEN-END:variables
}
