/* 
 * Copyright PT Len Industri (Persero) 

 *  
 * TO PT LEN INDUSTRI (PERSERO), AS APPLICABLE, AND SHALL NOT BE USED IN ANY WAY
 * OTHER THAN BEFOREHAND AGREED ON BY PT LEN INDUSTRI (PERSERO), NOR BE REPRODUCED
 * OR DISCLOSED TO THIRD PARTIES WITHOUT PRIOR WRITTEN AUTHORIZATION BY
 * PT LEN INDUSTRI (PERSERO), AS APPLICABLE
 */

package org.len.tdl.view.ryt;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import org.len.tdl.common.DataListener;
import org.len.tdl.common.StructCircle;
import org.len.tdl.common.StructFile;
import org.len.tdl.common.StructPolyline;
import org.len.tdl.common.StructText;
import org.len.tdl.common.StructTrack;
import org.len.tdl.core.DEF;
import org.len.tdl.thread_mc.UdpRx;
import org.len.tdl.thread_mc.UdpTx;

/**
 *
 * @author datalink1
 */

/**
 * 
 * This is DataGeneratorTester Jframe Form class
 */
public class DataGeneratorTester extends javax.swing.JFrame {

    /**
     * Reference Variables
     */
    private final DEF DEF = new DEF();
    private UdpTx udpTransmit = new UdpTx();
    private UdpRx udpReceive = new UdpRx();

    /**
     * Creates new form DataGenerator
     */
    public DataGeneratorTester() {
        initComponents();

        udpReceive.addListener(new DataListener() {
            @Override
            public void dataReceive(byte[] aData, int aType) {

                if (aData.length > 16) {
                    byte jam = aData[4];
                    byte menit = aData[5];
                    byte detik = aData[6];
                    String time = "[" + jam + ":" + menit + ":" + detik + ":] ";

                    if (aData[1] == DEF.TYPE_RX_MSG) {
                        byte[] data = new byte[aData.length - 8];
                        System.arraycopy(aData, 8, data, 0, data.length);
                        GUI_Show_Msg_Rx(data);
                    }
                    
                    
                    if (aData[1] == DEF.TYPE_TX_INFO) {
                        
                        if (aData[2] == DEF.INFO_TYPE_FTP_PROGRESS) {

                            byte[] data = new byte[aData.length - 8];
                            System.arraycopy(aData, 8, data, 0, data.length);
                            
                            int no_pack = data[2];
                            int jml_pack = data[3];
                            int msg_file_progress_tx = no_pack * 100 / jml_pack;
                            
                            GUI_Show_Progres_Msg_File(msg_file_progress_tx);
                        }
                        
                        if (aData[2] == DEF.INFO_TYPE_CURRENT_PTT) {

                            byte[] data = new byte[aData.length - 8];
                            System.arraycopy(aData, 8, data, 0, data.length);   
                        }           
                    }                    
                }
            }          
            @Override
            public void infoReceive(byte[] aData){     
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_own_npu = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_trak_tx = new javax.swing.JTable();
        btn_update_trak = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        sentTxt = new javax.swing.JTextField();
        sendtxtBtn = new javax.swing.JButton();
        rcvraddtxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txt_msg_file_filename = new javax.swing.JTextField();
        lbl_msg_file_size = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btn_send_file = new javax.swing.JButton();
        txt_msg_file_rcv_addr = new javax.swing.JTextField();
        lbl_msg_file_progress_tx = new javax.swing.JLabel();
        jProgressBar_msg_file_tx = new javax.swing.JProgressBar();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_obj_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_circle = new javax.swing.JTextField();
        sendcrclbtn = new javax.swing.JButton();
        delscrclbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmb_area_color_circle = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cmb_line_width_circle = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        txt_notes_circle = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cmb_line_color_circle = new javax.swing.JComboBox();
        chb_enable_properties_circle = new javax.swing.JCheckBox();
        txt_dest_circle = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        sendplbtn = new javax.swing.JButton();
        delsplbtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_polyline_long = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cmb_area_color_polyline = new javax.swing.JComboBox();
        cmb_line_width_polyline = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_notes_polyline = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_obj_no_polyline = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cmb_line_color_polyline = new javax.swing.JComboBox();
        chb_enable_properties_polyline = new javax.swing.JCheckBox();
        cmb_line_type_polyline = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cmb_arrow_type_polyline = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        txt_dest_polyline = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ip_address_local = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_port_udp_local = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_port_udp_remote = new javax.swing.JTextField();
        txt_ip_address_remote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_send_txt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        msg_receive_txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_own_npu.setText("4");
        txt_own_npu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_own_npuActionPerformed(evt);
            }
        });

        jTable_trak_tx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1.0),  new Double(130.111),  new Double(20.111),  new Double(10.0),  new Double(50.1),  new Double(44.0),  new Double(7.0)},
                { new Double(2.0),  new Double(130.222),  new Double(20.222),  new Double(20.0),  new Double(50.2),  new Double(33.0),  new Double(2.0)},
                { new Double(3.0),  new Double(130.333),  new Double(20.333),  new Double(30.0),  new Double(50.39),  new Double(22.0),  new Double(2.0)},
                { new Double(4.0),  new Double(130.444),  new Double(20.444),  new Double(40.0),  new Double(50.4),  new Double(12.0),  new Double(2.0)},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Trak no", "Longitude", "Latitude", "Speed", "Csr", "Height", "Attribute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_trak_tx);

        btn_update_trak.setText("update");
        btn_update_trak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_trakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_trak, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btn_update_trak)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Trak", jPanel1);

        jPanel7.setBackground(java.awt.SystemColor.activeCaptionBorder);

        sentTxt.setText("abc1234567890");

        sendtxtBtn.setText("send txt to");
        sendtxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtxtBtnActionPerformed(evt);
            }
        });

        rcvraddtxt.setText("3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(sendtxtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rcvraddtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendtxtBtn)
                    .addComponent(rcvraddtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Text", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        lbl_msg_file_size.setText("File size = ");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_send_file.setText("send file to");
        btn_send_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_send_fileActionPerformed(evt);
            }
        });

        txt_msg_file_rcv_addr.setText("0");

        lbl_msg_file_progress_tx.setText("Tx = 0%");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(txt_msg_file_filename)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_msg_file_size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btn_send_file, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_msg_file_rcv_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_msg_file_progress_tx, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar_msg_file_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_msg_file_filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_msg_file_size)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send_file)
                    .addComponent(txt_msg_file_rcv_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar_msg_file_tx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_msg_file_progress_tx))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("File", jPanel8);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setText("Circle number");

        txt_obj_no.setText("1");

        jLabel10.setText("longitude, latitude, range");

        txt_circle.setText("104.665,80,36689");

        sendcrclbtn.setText("send  crcl");
        sendcrclbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendcrclbtnActionPerformed(evt);
            }
        });

        delscrclbtn.setText("del scrcl");
        delscrclbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delscrclbtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Area Color");

        cmb_area_color_circle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Color", "Red", "Green", "Blue", "Yellow", "Maroon", "Lime", "White" }));

        jLabel19.setText("Line Width");

        cmb_line_width_circle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0" }));

        jLabel22.setText("Notes");

        txt_notes_circle.setText("Jangan di bom");

        jLabel25.setText("Line Color");

        cmb_line_color_circle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Red", "Green", "Blue", "Yellow", "Maroon", "Lime", "White" }));

        chb_enable_properties_circle.setText("Enable properties");
        chb_enable_properties_circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_enable_properties_circleActionPerformed(evt);
            }
        });

        txt_dest_circle.setText("0");

        jLabel20.setText("Destination");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txt_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 274, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel22))
                                    .addGap(59, 59, 59)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_notes_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmb_line_width_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmb_area_color_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_line_color_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(175, 175, 175)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_obj_no, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel10)
                                    .addComponent(chb_enable_properties_circle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_dest_circle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sendcrclbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(delscrclbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(159, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_obj_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dest_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(txt_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chb_enable_properties_circle)
                            .addComponent(sendcrclbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cmb_area_color_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cmb_line_color_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_line_width_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(delscrclbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_notes_circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Circle", jPanel9);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        sendplbtn.setText("send  pl");
        sendplbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendplbtnActionPerformed(evt);
            }
        });

        delsplbtn.setText("del spl");
        delsplbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delsplbtnActionPerformed(evt);
            }
        });

        jLabel23.setText("longitude, latutude, ...");

        txt_polyline_long.setText("104.665, 80.123,103.22, 81.2, 105.21, 80.571");

        jLabel27.setText("Area Color");

        cmb_area_color_polyline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Color", "Red", "Green", "Blue", "Yellow", "Maroon", "Lime", "White" }));

        cmb_line_width_polyline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0" }));

        jLabel28.setText("Line Width");

        jLabel29.setText("Notes");

        txt_notes_polyline.setText("Hati-hati daerah musuh");

        jLabel30.setText("Polyline number");

        txt_obj_no_polyline.setText("1");

        jLabel31.setText("Line Color");

        cmb_line_color_polyline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Red", "Green", "Blue", "Yellow", "Maroon", "Lime", "White" }));

        chb_enable_properties_polyline.setText("Enable properties");
        chb_enable_properties_polyline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_enable_properties_polylineActionPerformed(evt);
            }
        });

        cmb_line_type_polyline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solid", "Dash", "Dot", "Dash Dot" }));

        jLabel41.setText("Line Type");

        jLabel42.setText("Arrow Type");

        cmb_arrow_type_polyline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Arrow", "Begin Arrow", "End Arrow", "Begin and End" }));

        jLabel21.setText("Destination");

        txt_dest_polyline.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_enable_properties_polyline)
                    .addComponent(txt_polyline_long, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_notes_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_line_width_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(cmb_line_color_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(cmb_area_color_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel41)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_line_type_polyline, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_arrow_type_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendplbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delsplbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(txt_obj_no_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txt_dest_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_dest_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(txt_obj_no_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_polyline_long, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chb_enable_properties_polyline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb_line_type_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sendplbtn))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(cmb_area_color_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(cmb_line_color_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delsplbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_line_width_polyline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_notes_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(cmb_arrow_type_polyline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Polyline", jPanel10);

        jLabel1.setText("IP Address");

        txt_ip_address_local.setText("localhost");
        txt_ip_address_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ip_address_localActionPerformed(evt);
            }
        });

        jLabel2.setText("Port");

        txt_port_udp_local.setText("8031");
        txt_port_udp_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_port_udp_localActionPerformed(evt);
            }
        });

        jButton1.setText("Set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Local UDP :");

        jLabel5.setText("Remote UDP :");

        jLabel6.setText("IP Address");

        jLabel7.setText("Port");

        txt_port_udp_remote.setText("8030");
        txt_port_udp_remote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_port_udp_remoteActionPerformed(evt);
            }
        });

        txt_ip_address_remote.setText("localhost");
        txt_ip_address_remote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ip_address_remoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_port_udp_local, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ip_address_local, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_port_udp_remote, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ip_address_remote, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_ip_address_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_port_udp_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ip_address_remote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_port_udp_remote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
        );

        jTabbedPane2.addTab("Connection", jPanel2);

        jLabel3.setText("Own PU");

        msg_send_txt.setColumns(20);
        msg_send_txt.setRows(5);
        jScrollPane1.setViewportView(msg_send_txt);

        msg_receive_txt.setColumns(20);
        msg_receive_txt.setRows(5);
        jScrollPane2.setViewportView(msg_receive_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_own_npu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_own_npu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Method to update tracks in table TX
 */
    private void GUI_Update_Trak_Tx() {

        byte owner = Byte.valueOf(txt_own_npu.getText());
        StructTrack trakTmp = new StructTrack();

        int row = jTable_trak_tx.getRowCount();
        for (int i = 0; i < row; i++) {
            if (jTable_trak_tx.getModel().getValueAt(i, 0) != null) {

                trakTmp.setLongitude((double) jTable_trak_tx.getModel().getValueAt(i, 1));
                trakTmp.setLatitude((double) jTable_trak_tx.getModel().getValueAt(i, 2));
                trakTmp.setSpeed((double) jTable_trak_tx.getModel().getValueAt(i, 3));
                trakTmp.setCourse((double) jTable_trak_tx.getModel().getValueAt(i, 4));
                trakTmp.setHeight((int) (double) jTable_trak_tx.getModel().getValueAt(i, 5));
                trakTmp.setAttribute((int) (double) jTable_trak_tx.getModel().getValueAt(i, 6));
                int trakno = (int) (double) jTable_trak_tx.getModel().getValueAt(i, 0);
                if (trakno == 1) {
                    trakTmp.setAttribute(7);
                }
                trakTmp.setNumber(trakno);
                trakTmp.setOwner(owner);

                byte[] trakBytes = trakTmp.getBytesTrack();
                byte[] tmp = new byte[40];
                tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
                tmp[1] = (byte) DEF.TYPE_TX_TRACK;
                tmp[2] = (byte) 0;

                System.arraycopy(trakBytes, 0, tmp, 8, trakBytes.length);
                udpTransmit.sendUdp(tmp);
            }
        }
    }

    /**
     * Reference Variables
     */
    private final byte MSG_TYPE_NACK = 0;
    private final byte MSG_TYPE_ACK = 1;
    private final byte MSG_TYPE_DRAW_CIRCLE = 2;
    private final byte MSG_TYPE_DEL_CIRCLE = 3;
    private final byte MSG_TYPE_DRAW_POLYLINE = 4;
    private final byte MSG_TYPE_DEL_POLYLINE = 5;
    private final byte MSG_TYPE_UPDATE_PARAM = 6;
    private final byte MSG_TYPE_TEXT = 7;
    private final byte MSG_TYPE_FTP = 8;

    /**
     * method to show received messages
     * @param data 
     */
    private void GUI_Show_Msg_Rx(byte[] data) {

        byte[] header_msg = new byte[8];
        byte[] data_msg = new byte[data.length - 8];

        System.arraycopy(data, 0, header_msg, 0, 8);
        System.arraycopy(data, 8, data_msg, 0, data_msg.length);

        int sender_address = header_msg[0];
        int msg_data_type = header_msg[2];

        switch (msg_data_type) {
            case MSG_TYPE_NACK:
                break;

            case MSG_TYPE_ACK:
                msg_receive_txt.append(" Recv ack from NPU " + sender_address + " :  OK\n");
                break;

            case MSG_TYPE_DRAW_CIRCLE:
                break;

            case MSG_TYPE_DEL_CIRCLE:
                break;

            case MSG_TYPE_DRAW_POLYLINE:
                break;

            case MSG_TYPE_DEL_POLYLINE:
                break;

            case MSG_TYPE_TEXT:
                break;

            case MSG_TYPE_FTP:
                break;
        }

        
    }

    /**
     * method to show progress of file messages
     * @param tx_persen 
     */
    private void GUI_Show_Progres_Msg_File(int tx_persen) {
        jProgressBar_msg_file_tx.setValue(tx_persen);
        lbl_msg_file_progress_tx.setText("Tx = " + tx_persen + "%");
    }

    private void txt_ip_address_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ip_address_localActionPerformed
    }//GEN-LAST:event_txt_ip_address_localActionPerformed

    private void txt_own_npuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_own_npuActionPerformed
    }//GEN-LAST:event_txt_own_npuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udpTransmit.setSocket(Integer.valueOf(txt_port_udp_remote.getText()), txt_ip_address_remote.getText());
        udpReceive.setSocket(Integer.valueOf(txt_port_udp_local.getText()), txt_ip_address_local.getText());
        udpReceive.receiveStart();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendtxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtxtBtnActionPerformed
        StructText text = new StructText();
        byte destination_address = Byte.valueOf(rcvraddtxt.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());
        int text_number = 0;

        byte[] data_text = text.getBytesText(sentTxt.getText(), text_number);
        byte[] tmp = new byte[8 + data_text.length];
        tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
        tmp[1] = (byte) DEF.TYPE_TX_MSG;
        tmp[2] = (byte) DEF.MSG_TYPE_TEXT;
        tmp[3] = (byte) source_address;
        tmp[4] = (byte) destination_address;

        System.arraycopy(data_text, 0, tmp, 8, data_text.length);
        udpTransmit.sendUdp(tmp);
        msg_send_txt.append(" Send text to NPU " + destination_address + " : " + sentTxt.getText() + "\n");
    }//GEN-LAST:event_sendtxtBtnActionPerformed
    private byte[] msg_file;
    public int MAX_FILE_LENGTH = 1024 * 1024;
    String filename;
    JFileChooser fileChooser = new JFileChooser();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            int msg_file_length = (int) selectedFile.length();
            txt_msg_file_filename.setText(selectedFile.getName());
            lbl_msg_file_size.setText("File size = " + msg_file_length + " bytes");
            try {
                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(selectedFile));
                msg_file = new byte[msg_file_length];
                bis.read(msg_file, 0, msg_file_length);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_send_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_send_fileActionPerformed
        String sfilename = txt_msg_file_filename.getText();

        byte destination_address = Byte.valueOf(txt_msg_file_rcv_addr.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());

        StructFile fileTx = new StructFile();
        byte[] data_file = fileTx.getBytesFile(sfilename, msg_file);

        byte[] tmp = new byte[8 + data_file.length];
        tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
        tmp[1] = (byte) DEF.TYPE_TX_MSG;
        tmp[2] = (byte) DEF.MSG_TYPE_FTP;
        tmp[3] = (byte) source_address;
        tmp[4] = (byte) destination_address;

        System.arraycopy(data_file, 0, tmp, 8, data_file.length);
        udpTransmit.sendUdp(tmp);
        msg_send_txt.append(" Send file to NPU " + destination_address + " : " + sfilename + "\n");
    }//GEN-LAST:event_btn_send_fileActionPerformed

    private void sendcrclbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendcrclbtnActionPerformed
        StructCircle circle = new StructCircle();
        byte destination_address = Byte.valueOf(txt_dest_circle.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());
        int circle_number = Integer.valueOf(txt_obj_no.getText());
        String scircle = txt_circle.getText();

        if (chb_enable_properties_circle.isSelected()) {
            int idx_area_color = cmb_area_color_circle.getSelectedIndex();
            int idx_line_color = cmb_line_color_circle.getSelectedIndex();
            int idx_line_width = cmb_line_width_circle.getSelectedIndex();
            String notes = txt_notes_circle.getText();
            byte[] property = circle.setProperties(idx_area_color, idx_line_color, idx_line_width, notes);
            byte[] data_circle = circle.getBytesCircle(scircle, circle_number, property);

            byte[] tmp = new byte[8 + data_circle.length];
            tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
            tmp[1] = (byte) DEF.TYPE_TX_MSG;
            tmp[2] = (byte) DEF.MSG_TYPE_DRAW_CIRCLE;
            tmp[3] = (byte) source_address;
            tmp[4] = (byte) destination_address;

            System.arraycopy(data_circle, 0, tmp, 8, data_circle.length);
            udpTransmit.sendUdp(tmp);
            msg_send_txt.append(" Send Circle : " + txt_circle.getText() + " Notes : " + notes + "\n");
        } else {
            byte[] data_circle = circle.getBytesCircle(scircle, circle_number);

            byte[] tmp = new byte[8 + data_circle.length];
            tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
            tmp[1] = (byte) DEF.TYPE_TX_MSG;
            tmp[2] = (byte) DEF.MSG_TYPE_DRAW_CIRCLE;
            tmp[3] = (byte) source_address;
            tmp[4] = (byte) destination_address;

            System.arraycopy(data_circle, 0, tmp, 8, data_circle.length);
            udpTransmit.sendUdp(tmp);
            msg_send_txt.append(" Send Circle : " + txt_circle.getText() + "\n");
        }
    }//GEN-LAST:event_sendcrclbtnActionPerformed

    private void delscrclbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delscrclbtnActionPerformed
        int circle_number = Integer.valueOf(txt_obj_no.getText());
        byte destination_address = Byte.valueOf(rcvraddtxt.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());

        StructCircle circle = new StructCircle();
        byte[] data_circle = circle.getBytesDeleteCircle(circle_number);

        byte[] tmp = new byte[8 + data_circle.length];
        tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
        tmp[1] = (byte) DEF.TYPE_TX_MSG;
        tmp[2] = (byte) DEF.MSG_TYPE_DEL_CIRCLE;
        tmp[3] = (byte) source_address;
        tmp[4] = (byte) destination_address;

        System.arraycopy(data_circle, 0, tmp, 8, data_circle.length);
        udpTransmit.sendUdp(tmp);
        msg_send_txt.append(" Send Delete circle  \n");

    }//GEN-LAST:event_delscrclbtnActionPerformed

    private void chb_enable_properties_circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_enable_properties_circleActionPerformed
    }//GEN-LAST:event_chb_enable_properties_circleActionPerformed

    private void sendplbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendplbtnActionPerformed

        int idx_area_color = cmb_area_color_polyline.getSelectedIndex();
        int idx_line_color = cmb_line_color_polyline.getSelectedIndex();
        int idx_line_width = cmb_line_width_polyline.getSelectedIndex();
        int idx_line_type = cmb_line_type_polyline.getSelectedIndex();
        int idx_arrow_type = cmb_arrow_type_polyline.getSelectedIndex();

        StructPolyline polyline = new StructPolyline();
        byte destination_address = Byte.valueOf(txt_dest_circle.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());
        int polyline_number = Integer.valueOf(txt_obj_no_polyline.getText());
        String string_polyline = txt_polyline_long.getText();

        if (chb_enable_properties_polyline.isSelected()) {

            String notes = txt_notes_polyline.getText();
            byte[] property = polyline.setProperties(idx_area_color, idx_line_color, idx_line_width, idx_line_type, idx_arrow_type, notes);
            byte[] data_polyline = polyline.getBytesPolyline(string_polyline, polyline_number, property);
            
            byte[] tmp = new byte[8 + data_polyline.length];
            tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
            tmp[1] = (byte) DEF.TYPE_TX_MSG;
            tmp[2] = (byte) DEF.MSG_TYPE_DRAW_POLYLINE;
            tmp[3] = (byte) source_address;
            tmp[4] = (byte) destination_address;

            System.arraycopy(data_polyline, 0, tmp, 8, data_polyline.length);
            udpTransmit.sendUdp(tmp);
            msg_send_txt.append(" Send polyline  " + txt_polyline_long.getText() + " Notes : " + notes + "\n");

        } else {
            byte[] data_polyline = polyline.getBytesPolyline(string_polyline, polyline_number);

            byte[] tmp = new byte[8 + data_polyline.length];
            tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
            tmp[1] = (byte) DEF.TYPE_TX_MSG;
            tmp[2] = (byte) DEF.MSG_TYPE_DRAW_POLYLINE;
            tmp[3] = (byte) source_address;
            tmp[4] = (byte) destination_address;

            System.arraycopy(data_polyline, 0, tmp, 8, data_polyline.length);
            udpTransmit.sendUdp(tmp);
            msg_send_txt.append(" Send polyline  " + txt_polyline_long.getText() + "\n");
        }
    }//GEN-LAST:event_sendplbtnActionPerformed

    private void delsplbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delsplbtnActionPerformed
        int polyline_number = Integer.valueOf(txt_obj_no_polyline.getText());
        byte destination_address = Byte.valueOf(txt_dest_polyline.getText());
        byte source_address = Byte.valueOf(txt_own_npu.getText());

        StructPolyline polyline = new StructPolyline();
        byte[] data_polyline = polyline.getBytesDeletePolyline(polyline_number);

        byte[] tmp = new byte[8 + data_polyline.length];
        tmp[0] = (byte) DEF.TOPIC_CCD2CORE;
        tmp[1] = (byte) DEF.TYPE_TX_MSG;
        tmp[2] = (byte) DEF.MSG_TYPE_DEL_POLYLINE;
        tmp[3] = (byte) source_address;
        tmp[4] = (byte) destination_address;

        System.arraycopy(data_polyline, 0, tmp, 8, data_polyline.length);
        udpTransmit.sendUdp(tmp);
        msg_send_txt.append(" Send Delete polyline  \n");
    }//GEN-LAST:event_delsplbtnActionPerformed

    private void chb_enable_properties_polylineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_enable_properties_polylineActionPerformed
    }//GEN-LAST:event_chb_enable_properties_polylineActionPerformed

    private void btn_update_trakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_trakActionPerformed
        GUI_Update_Trak_Tx();
    }//GEN-LAST:event_btn_update_trakActionPerformed

    private void txt_port_udp_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_port_udp_localActionPerformed
    }//GEN-LAST:event_txt_port_udp_localActionPerformed

    private void txt_port_udp_remoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_port_udp_remoteActionPerformed
    }//GEN-LAST:event_txt_port_udp_remoteActionPerformed

    private void txt_ip_address_remoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ip_address_remoteActionPerformed
    }//GEN-LAST:event_txt_ip_address_remoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataGeneratorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataGeneratorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataGeneratorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataGeneratorTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataGeneratorTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send_file;
    private javax.swing.JButton btn_update_trak;
    private javax.swing.JCheckBox chb_enable_properties_circle;
    private javax.swing.JCheckBox chb_enable_properties_polyline;
    private javax.swing.JComboBox cmb_area_color_circle;
    private javax.swing.JComboBox cmb_area_color_polyline;
    private javax.swing.JComboBox cmb_arrow_type_polyline;
    private javax.swing.JComboBox cmb_line_color_circle;
    private javax.swing.JComboBox cmb_line_color_polyline;
    private javax.swing.JComboBox cmb_line_type_polyline;
    private javax.swing.JComboBox cmb_line_width_circle;
    private javax.swing.JComboBox cmb_line_width_polyline;
    private javax.swing.JButton delscrclbtn;
    private javax.swing.JButton delsplbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar_msg_file_tx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable_trak_tx;
    private javax.swing.JLabel lbl_msg_file_progress_tx;
    private javax.swing.JLabel lbl_msg_file_size;
    private javax.swing.JTextArea msg_receive_txt;
    private javax.swing.JTextArea msg_send_txt;
    private javax.swing.JTextField rcvraddtxt;
    private javax.swing.JButton sendcrclbtn;
    private javax.swing.JButton sendplbtn;
    private javax.swing.JButton sendtxtBtn;
    private javax.swing.JTextField sentTxt;
    private javax.swing.JTextField txt_circle;
    private javax.swing.JTextField txt_dest_circle;
    private javax.swing.JTextField txt_dest_polyline;
    private javax.swing.JTextField txt_ip_address_local;
    private javax.swing.JTextField txt_ip_address_remote;
    private javax.swing.JTextField txt_msg_file_filename;
    private javax.swing.JTextField txt_msg_file_rcv_addr;
    private javax.swing.JTextField txt_notes_circle;
    private javax.swing.JTextField txt_notes_polyline;
    private javax.swing.JTextField txt_obj_no;
    private javax.swing.JTextField txt_obj_no_polyline;
    private javax.swing.JTextField txt_own_npu;
    private javax.swing.JTextField txt_polyline_long;
    private javax.swing.JTextField txt_port_udp_local;
    private javax.swing.JTextField txt_port_udp_remote;
    // End of variables declaration//GEN-END:variables
}